### ISSUE TITLE
RDMA write problems

### ISSUE THREAD

**Issue by dylanede** [gpudirect/libgdsync#93] opened 2020-02-24 17:51 UTC
Hi, and thanks for your efforts on GPUDirect Async.

I'm trying to perform an RDMA write from GPU memory using libgdsync. First, is this supported? None of the tests appear to test this.

I am trying to do an RDMA write from GPU memory on one machine to GPU memory on another machine, using `gds_prepare_send` and `gds_stream_post_send`. I have found that the desired range of memory on the remote machine is indeed written to, however what is written is all zeroes, not the contents of the source memory I specified. Another problem is that no CQE appears in the sending CQ to notify that the RDMA write has completed (polling on the CQ never produces an entry and waiting in a CUDA stream on the CQ blocks the stream forever). I am not seeing any async events to suggest an error either.

I am allocating the CUDA memory on both ends using normal `cuMemAlloc` calls. Do I need to perhaps map or pin this memory myself? The code in "tests" does not seem to need to do this though for normal sends and receives.

I set up the memory region on the sending machine with flags set to zero, and on the receiving machine they're set to `IBV_ACCESS_LOCAL_WRITE | IBV_ACCESS_REMOTE_WRITE`.

I do not post any receive buffers on either machine, as I am only doing RDMA writes.

I set up the work request as follows:

```C++
struct ibv_sge gather = {
    .addr = (uintptr_t)gpu_mem,
    .length = 4,
    .lkey = mr_lkey
};
gds_send_wr ewr = {
    .wr_id = 1,
    .next = nullptr,
    .sg_list = &gather,
    .num_sge = 1,
    .exp_opcode = IBV_EXP_WR_RDMA_WRITE,
    .wr = {
        .rdma = {
            .remote_addr = (uintptr_t)client_gpu_mem_addr,
            .rkey = client_rkey
        }
    },
    .comp_mask = 0
};
```

Thanks in advance.

**Comment by dylanede** [comment] 2020-02-24 17:55
Turns out it was the flags on the sending memory region. I had them as zero, but setting them to `IBV_ACCESS_REMOTE_WRITE | IBV_ACCESS_REMOTE_READ | IBV_ACCESS_LOCAL_WRITE` made things work. I don't understand why this is necessary though, as surely only local read access is needed, and that's always given?

**Comment by dylanede** [comment] 2020-02-24 18:00
Though I am still not getting any notification in the sending CQ that the write is complete. Re-opening.

**Comment by dylanede** [comment] 2020-02-25 13:49
Setting the `exp_send_flags` field to `IBV_EXP_SEND_SIGNALED` allowed the CQE to appear, however I haven't found any documentation anywhere about this. If anyone has a link to documentation of this I would very much appreciate this.

I'm still leaving this issue open because as far as I can tell zero flags should be necessary on the sending side of an RDMA write, instead of the ones I had to add to get it to work.

**Comment by drossetti** [comment] 2020-02-26 01:08
@dylanede verbs are low-level APIs, not really meant for the average user.
There is some documentation at https://www.mellanox.com/related-docs/prod_software/RDMA_Aware_Programming_user_manual.pdf, but the real reference is the code, e.g. UCX, openmpi/openib_btl, etc.
libgdsync is as low level as verbs.
There are some very basic tests in libgdsync/tests/.
I suggest that in your apps, you should use github.com/gpudirect/libmp rather than libgdsync.

**Comment by drossetti** [comment] 2020-02-26 01:09
closing as not a bug

**Closed as completed by drossetti** 2020-02-26 01:09 UTC
Labels: question

**Comment by bmerry** [comment] 2022-08-15 15:02
@dylanede did you ever get any closure as to why you got all zeroes without the magic flags or why that's not considered a bug? I'm not using libgdsync (I'm using ibverbs directly) but have run into a very similar problem just with SEND, where if I omit IBV_ACCESS_LOCAL_WRITE I don't get the correct results.

**Comment by dylanede** [comment] 2022-08-16 11:28
@bmerry unfortunately not.
