### ISSUE TITLE
couldn't run gds_kernel_latency with allocating CQ or DBREC on GPU Mem

### ISSUE THREAD

**Issue by brave-hannah** [gpudirect/libgdsync#44] opened 2018-03-19 09:03 UTC
Using your master version code, I run GPUDirect Async with RX CQ and DBREC allocated in GPU mem to compare with in Host mem. 
But I always got the same error prints like 
"gds_create_cp() error 14 in ibv_exp_create_cq, old errno 22"
or 
"gds_create_qp() error in ibv_exp_create_qp", while the dmesg dumps "ib_umem_get: failed to get user pages, nr_pages=1".
I have checked that my GPU and mlx5 are the PHB topology and gdrdrv.ko is running correctly because tests you providing are running successfully. And Everything goes well if I use Host mem. 
So, why does this happen? Maybe some bugs there I think.

**Comment by brave-hannah** [comment] 2018-03-23 07:46
anyone knows the reason?

**Comment by drossetti** [comment] 2018-04-09 13:33
This issue is ortogonal to libgdsync. Most probably your machine misses the requirements for GPUDirect RDMA, e.g. you did not install the nv_peer_mem, or you don’t have an appropriate OFED

**Comment by brave-hannah** [comment] 2018-04-10 02:09
The version of mlnx is 4.2 used in my server. And the service nv_peer_mem and gdrcopy are started automatically when system boots up.  It's so weird.

**Comment by drossetti** [comment] 2018-04-14 02:40
stock libmlx5 does not support creation of CQ/DBREC on GPU mem.
we created experimental changes to do that which are not productize in MLNX OFED.

**Comment by drossetti** [comment] 2018-04-28 22:38
the relevant highly experimental code in in the peermem branches of both libmlx5 and mlxn-ofa_kernel.
I suggest to NOT use that code for anything other than personal education.
closing as not a bug

**Closed by drossetti** 2018-04-28 22:38 UTC
Labels: question
